KEY = db254b5cd61744d39a2deebd9c361444
###
# Complex Search
GET https://api.spoonacular.com/recipes/complexSearch?apiKey=db254b5cd61744d39a2deebd9c361444&cuisine=italian

###
# Random Recipes
GET https://api.spoonacular.com/recipes/random?apiKey=db254b5cd61744d39a2deebd9c361444&number=9

###
# Find by Ingredients
GET https://api.spoonacular.com/recipes/findByIngredients?apiKey=db254b5cd61744d39a2deebd9c361444&ingredients=steak

###
# Menu Item
GET https://api.spoonacular.com/food/menuItems/search?query=miso+salmon&apiKey=db254b5cd61744d39a2deebd9c361444&419357&query=419357

###
# Food jokes
GET https://api.spoonacular.com/food/jokes/random?apiKey=db254b5cd61744d39a2deebd9c361444

###
# Similar Food
GET https://api.spoonacular.com/recipes/7538/similar?apiKey=db254b5cd61744d39a2deebd9c361444

###
# Analyzed instructions
GET https://api.spoonacular.com/recipes/1068494/analyzedInstructions?apiKey=db254b5cd61744d39a2deebd9c361444

###

GET https://api.spoonacular.com/recipes/695486/information?includeNutrition=false&apiKey=db254b5cd61744d39a2deebd9c361444

###
# Get recipes in bulk
GET https://api.spoonacular.com/recipes/informationBulk?ids=715538,716429&apiKey=db254b5cd61744d39a2deebd9c361444

###
# Get recipe ingredients by ID
GET https://api.spoonacular.com/recipes/1003464/ingredientWidget.json?apiKey=db254b5cd61744d39a2deebd9c361444

###
# Connect with meal plan, need username and hash
POST https://api.spoonacular.com/users/connect?apiKey=db254b5cd61744d39a2deebd9c361444

Content-Type: application/json
{
  "username": "username",
  "firstName": "Firstname",
  "lastName": "Lastname",
  "email": "john@demo.com",
}

##################################################
# EDAMAM API
##################################################

# Search

# API ID = 1bfa73e6
# API KEY = 59669656fdf109339b840b29caad7d34
###

GET https://api.edamam.com/search?app_id=1bfa73e6&app_key=59669656fdf109339b840b29caad7d34&to=5&q=cheeseburger

###

GET https://api.edamam.com/search?q=chicken&app_id=1bfa73e6&app_key=59669656fdf109339b840b29caad7d34&from=0&to=3&calories=591-722&health=alcohol-free

###



GET https://api.edamam.com/search?app_id=1bfa73e6&app_key=59669656fdf109339b840b29caad7d34&r=http://www.edamam.com/ontologies/edamam.owl#recipe_10a60a65da566ba8a57206502bbf3cbf